In [5]:
import chess
import chess.uci
import chess.pgn
import sys,os
import numpy as np
import torch
import io
import pandas as pd
import concurrent
import dill
%load_ext autoreload

%autoreload 2

In [6]:
import torch,dill
import matplotlib.pyplot as plt
from oil.utils.utils import Eval, cosLr
from chess_dataset import ChessDataset, legal_opponent_moves,legal_moves

In [7]:
startfen = chess.Board().fen()
r = torch.arange(64)[:,None,None]

In [10]:
torch.sum(r.float()*legal_moves(startfen).float(),dim=0)

tensor([[0., 0., 0.,  ..., 0., 0., 0.]])

In [16]:
torch.sum(r.float()*legal_moves(startfen).reshape(64,8,8).float(),dim=0)

tensor([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 9.,  9., 11., 11., 12., 19., 14., 21.],
        [ 8.,  9., 10., 11., 12., 13., 14., 15.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [17]:
torch.sum(r.float()*legal_opponent_moves(startfen).reshape(64,8,8).float(),dim=0)

tensor([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
        [ 48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.],
        [105.,  49., 107.,  51.,  52., 115.,  54., 117.],
        [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.]])